#!/bin/sh /etc/rc.common
# Copyright (C) 2018-2020 Lienol <lawlienol@gmail.com>
# Improve by xiaozhuai <xiaozhuai7@gmail.com>
# Improve by superzjg <superzjg@gmail.com>

START=99
USE_PROCD=1

LOG_PATH="/var/log/filebrowser.log"

echolog() {
	echo -e "$(date "+%Y-%m-%d %H:%M:%S"): $1" >> $LOG_PATH
}

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get filebrowser.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}
allow_wan=$(config_t_get global allow_wan 0)
firewall_set=$(config_t_get global firewall_set force)

set_firewall() {
	if [ "$external_access" = "allow" ]; then
		[ "$firewall_set" == "no" ] && return 0
		if [ "$firewall_set" == "check" ] && [ "$(uci -q get firewall.filebrowser_auto.proto)" == "tcp" ];then
			[ "$PORT" == "$(uci -q get firewall.filebrowser_auto.dest_port)" ] && return 0
		fi
		uci -q delete firewall.filebrowser_auto
		uci set firewall.filebrowser_auto=rule
		uci set firewall.filebrowser_auto.name="filebrowser_auto"
		uci set firewall.filebrowser_auto.target="ACCEPT"
		uci set firewall.filebrowser_auto.src="wan"
		uci set firewall.filebrowser_auto.proto="tcp"
		uci set firewall.filebrowser_auto.dest_port="$PORT"
		uci set firewall.filebrowser_auto.enabled="1"
		uci commit firewall
		/etc/init.d/firewall reload >/dev/null 2>&1
	elif [ "$external_access" = "deny" ]; then
		if [ -n "$(uci -q show firewall.filebrowser_auto)" ]; then
			uci -q delete firewall.filebrowser_auto
			uci commit firewall
			/etc/init.d/firewall reload >/dev/null 2>&1
		fi   
	fi
}

start_service() {
	ENABLED=$(config_t_get global enable 0)
	[ "$ENABLED" = "0" ] && return
	
	ADDRESS=$(config_t_get global address 0.0.0.0)
	PORT=$(config_t_get global port 8088)
	DATABASE=$(config_t_get global database /etc/filebrowser.db)
	SSL=$(config_t_get global ssl 0)
	SSL_CERT=$(config_t_get global ssl_cert)
	SSL_KEY=$(config_t_get global ssl_key)
	ROOT_PATH=$(config_t_get global root_path /)
	extrFlag=$(config_t_get global extrFlag)
	executable_directory=$(config_t_get global executable_directory /tmp)

	[ ! -f "$executable_directory/filebrowser" ] && {
		(
		sleep 2
		echolog "---> No binary executable file 'filebrowser' found in the specified directory $executable_directory. Please download first!"
		echolog "---> 指定的目录 $executable_directory 下没有二进制执行文件 filebrowser ，请先下载！"
		) &
		return 1
	}
	[ -x "$executable_directory/filebrowser" ] || chmod 0755 "$executable_directory/filebrowser"
	
	# 服务启动是 procd 在函数退出后统一处理，启动后执行特定代码需子进程后台执行
	(
	[ -f "$DATABASE" ] || {
		true >$LOG_PATH
		i=16; str=""
		until [ -n "$str" ]; do
		i=$(($i - 1))
		[ "$i" -lt 0 ] && break
		str=$(grep 'password' $LOG_PATH |grep 'admin' |awk '{print $NF}')
		sleep 1
		done
		echolog "---> First startup. Please change the initial password for the default user admin promptly, which is: ${str}"
		echolog "---> 首次启动，请及时更改用户 admin 的初始密码：${str}"
		}
	) &

	SSL_PARAMS=""
	if [ $SSL -eq 1 ];then
		[ -n "$SSL_CERT" ] && [ -n "$SSL_KEY" ] && SSL_PARAMS="-t $SSL_CERT -k $SSL_KEY"
	fi
	[ "$allow_wan" -eq "1" ] && external_access="allow" || external_access="deny"
	set_firewall
	
	procd_open_instance filebrowser
	procd_set_param command /bin/sh
	procd_append_param command -c "exec $executable_directory/filebrowser -a $ADDRESS -p $PORT -r $ROOT_PATH -d $DATABASE $SSL_PARAMS $extrFlag >> $LOG_PATH 2>&1"
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "filebrowser"
}

stop_service() {
	# rm -rf $LOG_PATH
	[ "$allow_wan" != "1" -o "$firewall_set" == "force" ] && external_access="deny"
	set_firewall
}

# 重定义reload否则可能不执行stop_service
reload_service() {
	stop
	sleep 1
	start
}
